# Generated by Django 3.1.13 on 2021-07-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='作成日'),
        ),
    ]
