# Generated by Django 3.1.13 on 2021-07-24 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
